name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Nomos Backend
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          password: ${{ secrets.SSH_PASSWORD }} # Password
          script: |
            cd ..
            cd home/tiny-house/tiny-house-frontend 
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pm2 delete "Nomos Web"
            npm install
            ng build --prod
            cd ..
            cp -R tiny-house-frontend/dist/Nomos-Web/* tiny-house-backend/client
            cd home/tiny-house/tiny-house-backend
            pm2 start server.js --name "Nomos Web"
            
            
